version: "3.9"
services:
  app:
    image: tests-framework:latest
    working_dir: /api-tests
    build: .
    volumes:
      - allure-results:/api-tests/target/allure-results

  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
    ports:
    - "5050:5050"
    volumes:
      - allure-results:/app/allure-results

  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5252:5252"

volumes:
  allure-results:
